### ISSUE TITLE
[FEATURE]: Get PDF links that contains gas prices from JORAM

### ISSUE THREAD

**Issue by carlosrsabreu** [carlosrsabreu/devo-abastecer#10]
## Expected Behavior

At this moment, we have a scrapper that reads a JORAM PDF file and returns a `dictionary` with the gas prices. You can check the scrapper in this [file](https://github.com/carlosrsabreu/devo-abastecer/blob/main/joram.py).

- The PDF files can be found in this [link](https://joram.madeira.gov.pt/joram/2serie/);
- The weekly gas prices are issued on Thursdays or Fridays (most of them on Fridays);
- The **2.º Suplemento** PDF files are the ones that contain gas prices (but not all of them).

You can check some examples here:

![image](https://user-images.githubusercontent.com/18048652/179629628-bd05dfc3-a5b6-4f55-827a-84126bc1973d.png)

## Actual Behavior

The gas prices are retrieved from the [Direção Regional de Economia e Transportes Terrestres](https://www.madeira.gov.pt/drett) website. 

However, these prices are not updated every Friday (as the JORAM document is issued with gas prices for the next week), so sometimes we can get the gas prices after the current week and don't have the info in time.

To check how we retrieve the gas prices at this moment, check [this file](https://github.com/carlosrsabreu/devo-abastecer/blob/main/script.py
).

**Comment by joaoofreitas** [comment]
Shall be done.

**Comment by HarryVasanth** [comment]
@joaoofreitas @carlosrsabreu 

This will be a good start, I guess 💁‍♂️:

```py
import requests
from bs4 import BeautifulSoup
import datetime

# Current year
current_year = str(datetime.datetime.now().year)

# JORAM URL
url = f'https://joram.madeira.gov.pt/joram/2serie/Ano%20de%20{current_year}/'

response = requests.get(url)
html = response.text
soup = BeautifulSoup(html, 'html.parser')
links = soup.find_all('a')

# Find the newest file by sorting the list of links in reverse order and extract the name of the file from the link
pdf_links = [link for link in links if link['href'].endswith('.pdf')]
newest_pdf_link = sorted(pdf_links, reverse=True)[0]
newest_pdf_filename = newest_pdf_link['href'].split('/')[-1]

# Use the filename to scrape the content
print(newest_pdf_filename)
```

**Comment by joaoofreitas** [comment]
The current Issue is stale. 

The branch I was working on is: https://github.com/carlosrsabreu/devo-abastecer/tree/feat/pdf-linking
This issue is currently stale due to inconsistency in JORAM paper publishing and my lack of time.  

Following this, feel free to make this move @HarryVasanth. 
Always a pleasure to work with you :)

**Comment by HarryVasanth** [comment]
@joaoofreitas I'll get to it at some point. At least, I will try to. 
Likewise! 😊

**Comment by Dntfreitas** [comment]
Another approach: https://cloud.google.com/vision/docs/pdf. This enables to get structured text extracted from a PDF file.

**Comment by joaoofreitas** [comment]
@Dntfreitas Even though I like the idea, and that it's quite simple to implement. It would create a dependency to Google Services. Which can be perfectly avoidable.

Is there a way to use the AI independently that I am missing out?

Anyways, this is a matter of decision making by @carlosrsabreu.

Feedback is appreciated too:
@13dev 
@HarryVasanth

**Comment by carlosrsabreu** [comment]
@joaoofreitas yes, we can avoid creating that dependency. Also, @Dntfreitas said that is a paid service (the first 1000 requests are free), but I believe we can do it without using it.

We can follow the initial idea of having the scrapper made only by Python code.

Let's get a solution for this issue and we get the first stable version of the app, hopefully! 🙏

**Comment by HarryVasanth** [comment]
@joaoofreitas @carlosrsabreu 

I agree with keeping up with the original scraper. The fewer dependencies, the fewer things that we need to worry about getting deprecated. Also, keeping it primitive & minimal, means it's easier to fix it than going on an api witch-hunt.  💁

**Comment by Dntfreitas** [comment]
True. But humans are inconsistent. This week they write in one way, and the other week in a completely different way.

I agree; we should try first the original solution. If it does not work, move the solution that I proposed.

**Comment by carlosrsabreu** [comment]
> ## Expected Behavior
> At this moment, we have a scrapper that reads a JORAM PDF file and returns a `dictionary` with the gas prices. You can check the scrapper in this [file](https://github.com/carlosrsabreu/devo-abastecer/blob/main/joram.py).
> 
> * The PDF files can be found in this [link](https://joram.madeira.gov.pt/joram/2serie/);
> * The weekly gas prices are issued on Thursdays or Fridays (most of them on Fridays);
> * The **2.º Suplemento** PDF files are the ones that contain gas prices (but not all of them).
> 
> You can check some examples here:
> 
> ![image](https://user-images.githubusercontent.com/18048652/179629628-bd05dfc3-a5b6-4f55-827a-84126bc1973d.png)
> 
> ## Actual Behavior
> The gas prices are retrieved from the [Direção Regional de Economia e Transportes Terrestres](https://www.madeira.gov.pt/drett) website.
> 
> However, these prices are not updated every Friday (as the JORAM document is issued with gas prices for the next week), so sometimes we can get the gas prices after the current week and don't have the info in time.
> 
> To check how we retrieve the gas prices at this moment, check [this file](https://github.com/carlosrsabreu/devo-abastecer/blob/main/script.py).

**EDIT:** The **2.º Suplemento** PDF files sometimes are not the ones that contain gas prices (but not all of them). Here is an example: https://joram.madeira.gov.pt/joram/2serie/Ano%20de%202023/IISerie-020-2023-01-27Supl.pdf
For this reason, we should scrap all of them, so we can't create a rule to scrap just a few ones. 

@HarryVasanth @Dntfreitas @joaoofreitas @13dev

**Comment by joaoofreitas** [comment]
Let's bruteforce all of them. Should not be a problem.

**Comment by HarryVasanth** [comment]
@carlosrsabreu 
> For this reason, we should scrap all of them, so we can't create a rule to scrap just a few ones.

@joaoofreitas 
> Let's bruteforce all of them. Should not be a problem.

or... we sort it as we do, and iterate one at a time until we get to a valid fuel price? 🤔

```mermaid
graph TD
B[Sort PDFs by date]
B --> C[Check first PDF for *fuel price*]
C --> D{PDF contains *fuel price*?}
D -- Yes --> E[Stop iterating and use this PDF]
D -- No --> F[Check next PDF for *fuel price*]
F --> D
```

**Comment by joaoofreitas** [comment]
That's exactly the solution I was thinking about. 

Let's keep it on!

**Comment by HarryVasanth** [comment]
> That's exactly the solution I was thinking about.
> 
> Let's keep it on!

Done 😅
