### ISSUE TITLE
Plot generation from Jupyter Notebook

### ISSUE THREAD

**Issue by carlosrsabreu** [carlosrsabreu/devo-abastecer#14]
## Expected Behavior

We could generate and upload the plots from a Jupyter Notebook, as @HarryVasanth has suggested [here](https://github.com/carlosrsabreu/devo-abastecer/pull/11#pullrequestreview-1239893164).

## Actual Behavior

After having [this](https://github.com/carlosrsabreu/devo-abastecer/pull/11) PR merged, we'll have a gas variation from the last six months being deployed, having also the images being stored in the repo.

**Comment by HarryVasanth** [comment]
After looking further into it. I think this would add more complications than the solution suggested by @Dntfreitas. Would be better that way. This issue could be closed.
