### ISSUE TITLE
Retrieve gas prices

### ISSUE THREAD

**Issue by carlosrsabreu** [carlosrsabreu/devo-abastecer#5]
## Expected Behavior

The prices should be retrieved from the [JORAM](https://joram.madeira.gov.pt/joram/2serie/) website. The weekly gas prices are issued every Friday, in **2.º Suplemento**. You can check some examples here:

![image](https://user-images.githubusercontent.com/18048652/179629628-bd05dfc3-a5b6-4f55-827a-84126bc1973d.png)

## Actual Behavior

Right now, the gas prices are retrieved from the [Direção Regional de Economia e Transportes Terrestres](https://www.madeira.gov.pt/drett) website. However, these prices are not updated every Friday (as the JORAM document is issued with gas prices for the next week).

To check how we retrieve the gas prices at this moment, check [this file](https://github.com/carlosrsabreu/devo-abastecer/blob/main/script.py
).

**Comment by Dntfreitas** [comment]
Hum... are you sure that the prices are always in 2.º Suplemento Check this example: https://joram.madeira.gov.pt/joram/2serie/Ano%20de%202022/IISerie-143-2022-08-01Supl2.pdf

**Comment by Dntfreitas** [comment]
In the future, we can try this: https://cloud.google.com/document-ai

**Comment by joaoofreitas** [comment]
@carlosrsabreu I think we can close this.
